### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by iwasthesword** [ForaDoEixo/MapasBuilder#18]
Implementar algum tipo de cache para evitar sobrecargas no servidor

**Comment by iwasthesword** [comment]
A API do Mapas retorna `cache-control: no-store, no-cache, must-revalidate` no header, inutilizando a cache padrão do jQuery

**Comment by uira** [comment]
@brunosmartin e @rafaelchavesfreitas, vcs tem alguma sugestão de abordagem para implementar esse cache?

**Comment by leogermani** [comment]
Minha impressão é que tem q ser uma outra camada. Um cache com nginx, varnish, algo assim. Mas tem uns configs no config.php que dá pra ativar os caches. Vcs chegaram a olhar no conf-base?

**Comment by rafaelchavesfreitas** [comment]
Já que se trata de um plugin WordPress uma ideia é implementar no plugin um proxy para a api, como foi feito no tema Cultural, e neste um cache. 

Se o caminho for colocar um cache no nginx ou varnish tem que ser feito com muito cuidado, pois a mesma requisição não api pode ter retornos diferentes para usuários diferentes.

**Comment by iwasthesword** [comment]
@leogermani eu dei uma olhada no conf-base e parece que o cache ja está ligado. essas configurações refletem em algo relacionado aos headers retornados pela API? Porque mesmo ele aparentemente estando ligado, ele retorna no header isso: 
> `Cache-Control: no-store, no-cache, must-revalidate`
E isso impossibilita de usar pelo menos o cache local do ajax

**Comment by iwasthesword** [comment]
closes @ 4e1e1f265786b033d3d5537001ed99d65bc17679
