### ISSUE TITLE
Bug no api-metadata

### ISSUE THREAD

**Issue by iwasthesword** [ForaDoEixo/MapasBuilder#20]
Avaliar porque esse header não funciona no server de produção

**Comment by uira** [comment]
Isso é um problema do server, correto @Andreqlp ?

**Comment by iwasthesword** [comment]
Descobri que só estava funcionando no ambiente de dev por causa do proxy. O problema na verdade é por causa dos headers não estarem explicitamente definidos no servidor. 
> If you're doing CORS, the server has to be explicit about what headers the client is allowed to read. If you want to read X-My-CustomHeader in javascript, then this header should be in the server response:
> ```Access-Control-Expose-Headers: X-My-CustomHeader```

https://stackoverflow.com/a/44687480

No caso a proxy de CORS que eu estava usando resolvia esse problema expondo esses headers

**Comment by iwasthesword** [comment]
closes @ 4e1e1f265786b033d3d5537001ed99d65bc17679
